services:
  - type: web
    name: realestate-uae
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/out
    envVars:
      - key: NODE_VERSION
        value: 18
